version: '2.1'

services:
  localstack:
    image: localstack/localstack-full
    networks:
      - backend
    ports:
      - "4566:4566"
      - "4569:4569"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  backend:
    name: abp-sam-backend